version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

dotenv: ['.env']

vars:
  # Reserve 2 cores for system, minimum 1 job
  BUILD_JOBS: '{{if gt (sub numCPU 2) 0}}{{sub numCPU 2}}{{else}}1{{end}}'

env:
  # Strip IDE extension paths (e.g. VS Code globalStorage) from PATH so
  # IDE-bundled tools don't shadow project-pinned versions during builds
  PATH:
    sh: 'echo "$PATH" | tr ":" "\n" | grep -v "globalStorage" | paste -sd ":" -'
  CARGO_HOME: "{{.ROOT_DIR}}/.cache/cargo"
  CARGO_TARGET_DIR: "{{.ROOT_DIR}}/target"
  RUSTUP_TOOLCHAIN: nightly
  RUSTC_WRAPPER: sccache
  RUSTFLAGS: "-Zthreads={{.BUILD_JOBS}}"
  CARGO_BUILD_JOBS: "{{.BUILD_JOBS}}"

includes:
  cargo:
    taskfile: ./taskfiles/cargo.yml

tasks:
  default:
    desc: "Default task"
    cmds:
      - task --list

  install:
    desc: "Install deps"
    env:
      PATH: '{{env "HOME"}}/.local/bin:{{.ROOT_DIR}}/.cache/cargo/bin:{{env "PATH"}}'
      RUSTC_WRAPPER: ""
    cmds:
      - mise install
      - command -v rustup &> /dev/null || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - |
        if ! command -v sccache &> /dev/null; then
          if [[ "$(uname)" == "Darwin" ]]; then
            brew install sccache
          else
            sudo apt-get update && sudo apt-get install -y sccache
          fi
        fi
      - cargo install --locked rustlings
      - |
        if ! command -v cargo-nextest &> /dev/null; then
          case "$(uname -s)-$(uname -m)" in
            Darwin-arm64)  target="aarch64-apple-darwin" ;;
            Darwin-x86_64) target="x86_64-apple-darwin" ;;
            Linux-aarch64) target="aarch64-unknown-linux-gnu" ;;
            Linux-x86_64)  target="x86_64-unknown-linux-gnu" ;;
            *) echo "Unsupported platform, falling back to cargo install"; cargo install --locked cargo-nextest; exit 0 ;;
          esac
          curl -LsSf "https://get.nexte.st/latest/${target}" | tar xzf - -C "{{.ROOT_DIR}}/.cache/cargo/bin"
        fi
    status:
      - command -v sccache &> /dev/null
      - command -v cargo &> /dev/null
      - command -v rustlings &> /dev/null
      - command -v cargo-nextest &> /dev/null
    silent: true

  pre-commit:
    desc: "Run pre-commit hooks"
    cmds:
      - prek run --all-files

  lint:
    desc: "Run linters"
    cmds:
      - task: cargo:lint

  format:
    desc: "Run formatters"
    cmds:
      - task: cargo:format

  test:
    desc: "Run tests (Rust + Frontend)"
    cmds:
      - task: cargo:test

  build:timings:
    desc: "Analyze build performance bottlenecks"
    cmds:
      - task: cargo:build:timings

  repomix:
    desc: "Create llm snapshot of repo"
    preconditions:
      - sh: command -v repomix 2>/dev/null
        msg: "repomix is not installed. Install with: npm install -g repomix"
    cmds:
      - |
        repomix \
          --style markdown \
          --compress \
          --remove-comments \
          --remove-empty-lines \
          --truncate-base64
    sources:
      - "**/*.rs"
      - "**/*.toml"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.md"
      - "**/*.json"
      - ".repomix*"
    generates:
      - repomix-output.md
